# Generated by Django 5.1.7 on 2025-03-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
