# Generated by Django 5.1.6 on 2025-03-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanApplication',
        ),
        migrations.AddField(
            model_name='loan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=6.0, help_text='6% Monthly Interest', max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='tenure_months',
            field=models.IntegerField(default=4, help_text='Fixed tenure of 4 months'),
        ),
    ]
