# Generated by Django 5.1.7 on 2025-03-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_delete_loanapplication_loan_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='face_verifications/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='id_upload',
            field=models.ImageField(blank=True, null=True, upload_to='id_uploads/'),
        ),
    ]
