# Generated by Django 5.1.7 on 2025-03-07 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loan_face_image_loan_id_upload'),
    ]

    operations = [
    ]
