# Generated by Django 5.1.7 on 2025-03-10 13:32

import django.db.models.deletion
import loans.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_auto_20250307_1230'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='approved_at',
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor_id',
            field=models.ImageField(blank=True, null=True, upload_to=loans.models.user_upload_path),
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor_name',
            field=models.CharField(default='Unknown Guarantor', max_length=255),
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor_occupation',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor_phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to=loans.models.user_upload_path),
        ),
        migrations.AlterField(
            model_name='loan',
            name='id_upload',
            field=models.ImageField(blank=True, null=True, upload_to=loans.models.user_upload_path),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='tenure_months',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
    ]
